#!/usr/bin/env python3

import argparse
import sys

import openslide


def main(args=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("slide")
    parser.add_argument("property", nargs='*', help="Properties to print.  If not specified, all are printed")

    opts = parser.parse_args(args)

    slide = openslide.open_slide(opts.slide)
    if opts.property:
        for p in opts.property:
            print(p, "\t", slide.properties.get(p))
    else:
        for k, v in slide.properties.items():
            print(k, "\t", v)


if __name__ == '__main__':
    main(sys.argv[1:])
